default:
  image: maven:3.8.5-openjdk-17
  cache:
    paths:
      - .m2/repository/
      - .m2/settings.xml
      - target/

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - setup
  - build
  - test
  - publish

setup:
  stage: setup
  script:
    - echo "$MAVEN_SETTINGS" > .m2/settings.txt

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

publish:
  stage: publish
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
